# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  issue_comment:
    branches: 
     - master
    types:
     - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  autodeploy-flow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check for Autodeploy
      env:
        COMMENT_BODY: ${{ github.event.payload.comment.body }}
      if: startsWith($COMMENT_BODY, '!sailbot autodeploy')
      run: exit 1
  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repo
      uses: actions/checkout@v2

    # Install deps
    # - name: Install Deps
    #   run: npm ci

    # # # Check for auto deploy
    # - name: Run Autodeploy Check Step
    #   # uses: ./.github/actions/check-for-autodeploy
    #   if: startsWith(github.event.payload.comment.body, '!sailbot autodeploy')

    # # Black Box step
    # - name: Run Black Box Step
    #   uses: ./.github/actions/black-box
    #   needs: 

    # # Slack send
    # - name: Run Slack Notification Step
    #   uses: /.github/actions/slack-send
