# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  issue_comment:
    branches: 
     - master
    types:
     - created

env:
  DEPLOY_REQUESTED: ${{ startsWith(github.event.payload.comment.body, '!sailbot autodeploy') }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  autodeploy-flow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Check the comment body for the deploy command. If the command is not there, we fail the work flow.
    - name: Check for Autodeploy
      if: !env.DEPLOY_REQUESTED
      run: echo Autodeploy command found, starting workflow...

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repo
      if: !env.DEPLOY_REQUESTED
      uses: actions/checkout@v2

    # Install deps
    - name: Install Deps
      if: !env.DEPLOY_REQUESTED
      run: npm ci

    
    # - name: Get Pull Request Merge Commit SHA
    #   uses: 

   

    # # # Check for auto deploy
    # - name: Run Autodeploy Check Step
    #   # uses: ./.github/actions/check-for-autodeploy
    #   if: startsWith(github.event.payload.comment.body, '!sailbot autodeploy')

    # # Black Box step
    # - name: Run Black Box Step
    #   uses: ./.github/actions/black-box
    #   needs: 

    # # Slack send
    # - name: Run Slack Notification Step
    #   uses: /.github/actions/slack-send
